name: build
on: [ pull_request, push, workflow_dispatch ]

jobs:
  build:
    strategy:
      matrix:
        java: [ 17 ]
    runs-on: ubuntu-latest
    env:
      MAVEN_USER: ${{ secrets.MAVEN_USER }}
      MAVEN_PASS: ${{ secrets.MAVEN_PASS }}
    steps:

      - name: checkout repository
        uses: actions/checkout@v3

      - name: make gradle wrapper executable
        run: chmod +x ./gradlew

      - name: setup Java
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17
          cache: gradle

      - name: build
        run: ./gradlew buildOrPublish --stacktrace

      - name: capture build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: Artifacts
          path: build/libs/

      - name: publish to Modrinth and Curseforge
        uses: Kir-Antipov/mc-publish@v3.2
        with:
          modrinth-id: tEJPA4Ty
          modrinth-token: ${{ secrets.MODRINTH_TOKEN }}
          modrinth-featured: true

          curseforge-id: 696251
          curseforge-token: ${{ secrets.CURSEFORGE_TOKEN }}

          loaders: |
            fabric
            quilt

          version-type: alpha

          changelog: ${{ github.event.head_commit.message }}
